### ISSUE TITLE
某数字免费的壳都无法拖

### ISSUE THREAD

**Issue by cjycjw** [FeJQ/AUPK#1]
试了好几个都是修复后无法打开，看了一下文件格式，文件头格式都不对，没有dex魔术特征等，试了fupk3可以拖出来的包，这个工具脱出来修复后也是无法打开的，根本就不是dex格式。这个作者测试过吗？（ps: 完全刷了你的镜像测试的，其他的壳未测试。）

**Comment by FeJQ** [comment]
360会抹掉magic字段，如果工具修复后没有还原magic，就手动恢复一下吧

**Comment by cjycjw** [comment]
嗯，手工修复dex035后确实可以了！
